blueprint:
  name: Alarm Notification Hver 30. Minut
  description: Tjek hvert 30. minut, om ingen er hjemme, og alarmen ikke er tilkoblet. Send en pushbesked, hvis det er tilfældet.
  domain: automation
  input:
    person_entities:
      name: Personer
      description: Vælg de personer, der skal overvåges.
      selector:
        target:
          entity:
            domain: person
    alarm_entity:
      name: Alarm
      description: Vælg alarmkontrolpanelet.
      selector:
        entity:
          domain: alarm_control_panel
    notification_service:
      name: Pushbesked service
      description: Vælg notifikationsservicen til push-beskeder.
      selector:
        device:
          integration: mobile_app

trigger:
  - platform: time_pattern
    minutes: "/30"  # Kør hvert 30. minut

condition:
  - condition: and
    conditions:
      - condition: state
        entity_id: !input "alarm_entity"
        state: "disarmed"  # Alarmen er ikke aktiveret
      - condition: template
        value_template: >
          {{ expand(!input "person_entities") | selectattr('state', 'eq', 'not_home') | list | length == expand(!input "person_entities") | list | length }}

action:
  - service: notify.mobile_app_{{ device_id }}
    data:
      message: "Ingen er hjemme, og alarmen er ikke aktiveret. Husk at aktivere den!"
